general_settings:
  master_key: ${LITELLM_API_KEY}

model_list:
  - model_name: openai-gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: ${OPENAI_API_KEY}
      api_base: ${OPENAI_API_BASE:-https://api.openai.com/v1}
  - model_name: anthropic-claude-3-5-sonnet
    litellm_params:
      model: claude-3-5-sonnet-20240620
      api_key: ${ANTHROPIC_API_KEY}
      anthropic_version: ${ANTHROPIC_VERSION:-2023-06-01}
  - model_name: mistral-large
    litellm_params:
      model: mistral/mistral-large-latest
      api_key: ${MISTRAL_API_KEY}
      api_base: ${MISTRAL_API_BASE:-https://api.mistral.ai/v1}
